blog/urls.py
from django.views.generic import ListView
from django.urls import path
from .models import Post
from . import views

app_name = 'blog'
urlpatterns = [
    path('',
         ListView.as_view(
             queryset=
             Post.objects.all().order_by("-date")[:25],
             template_name="blog.html"
         ), name="blog"
         ),

    path('<int:pk>/',
         views.PostDetail.as_view(
             model=Post,
             template_name="post.html"
         ), name="post"
         ),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.index, name='home'),
]

mtgSite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls')),
    path('blog/', include('blog.urls')),
    path('user_auth/', include('user_auth.urls')),
    path('admin/', admin.site.urls),
]

user_auth/urls.py
from django.urls import path
from . import views

app_name = 'user_auth'
urlpatterns = [
    path('', views.user_login, name='login'),
    path('authenticate_user/', views.authenticate_user,
         name='authenticate_user'),
    path('logout/', views.logout_view,
         name='logout_user'),
    path('register_user/', views.register_user, name='register_user'),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Post(models.Model):
    """
    This class is used to create posts for the articles section of the site

    :param title: The title of the post
    :param body: The main body of text for a post
    :param date: The date the post was added, defaults to the current date
    :param author: The creator of a post, currently defaults to my name
    """
    # Default behaviour - Django creates primary keys for you
    title = models.CharField(max_length=140)
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    author = models.CharField(max_length=140, default="Murray Bosworth")

    class Meta:
        ordering = ['-date']

    # Returns the number of comments on a post
    @property
    def number_of_comments(self):
        """
        This allows us to track the number of comments attached to a post

        :return: The number of comments attached to a post

        :rtype: int
        """
        return Comment.objects.filter(blog_post=self).count()

    def __str__(self):
        return self.title


class Comment(models.Model):
    """
    This class is used to create comments for the articles section of the site

    :param blog_post: The post object the comment is attached to
    :param author: The author of the comment, taken from their username
    :param body: The body of the comment
    :param date_posted: The date the comment was added, defaults to the current date
    """
    # Create a class so users can add comments to blog posts
    # Tutorial found at https://dev.to/radualexandrub/how-to-create-a-comment-section-for-your-django-blog-3egp
    blog_post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    body = models.TextField()
    date_posted = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['date_posted']

    def __str__(self):
        return 'Comment {} by {}'.format(self.body, self.author)

home/models.py
from django.db import models

# Create your models here.

user_auth/models.py
from django.db import models

# Create your models here.

blog/forms.py
from .models import Comment
from django import forms


class CommentForm(forms.ModelForm):
    """
    Creates a new comment form object to be called by the PostDetail view
    """
    class Meta:
        model = Comment
        fields = ['body']

blog/views.py
from django.views.generic import DetailView
from .models import Comment
from .forms import CommentForm


# Create your views here.
class PostDetail(DetailView):
    """
    Creates an object as a subclass of DetailView to display posts on the website.
    """
    def get_context_data(self, **kwargs):
        """
        This method pulls the data for a post object to display it on the site.
        storing it in a dictionary

        :return: Returns the context data for a post including attached comments if there are any.
        If the user is authenticated it will also include the commentForm to allow them to leave
        a comment.
        """
        data = super().get_context_data(**kwargs)

        comments_connected = Comment.objects.filter(
            blog_post=self.get_object()).order_by('-date_posted')
        data['comments'] = comments_connected
        if self.request.user.is_authenticated:
            data['comment_form'] = CommentForm(instance=self.request.user)
        return data

    def post(self, request, *args, **kwargs):
        """
        This method receives the context data from the CommentForm and post it
        from within the class based PostDetail view

        :return: POSTs the new comment data to our server to be saved in our database
        """
        new_comment = Comment(body=request.POST.get('body'),
                              author=self.request.user,
                              blog_post=self.get_object())
        new_comment.save()
        return self.get(self, request, *args, **kwargs)

home/views.py
from django.shortcuts import render


# Create your views here.
def index(request):
    return render(request, "index.html")

user_auth/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse


# Create your views here.
def user_login(request):
    """
    Requests the authentication/login.html page be loaded
    """
    return render(request, 'authentication/login.html')


def authenticate_user(request):
    """
    Requests a user object from the server based on the username and password entered.
    If one exists the user is logged in and returned to the home page, if not they are
    returned to the login page.
    """
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(username=username, password=password)
    if user is None:
        return HttpResponseRedirect(
            reverse('user_auth:login')
        )
    else:
        login(request, user)
        return HttpResponseRedirect(
            reverse('home:home')
        )


# I followed this guide for creating a simple registration form -
# https://simpleisbetterthancomplex.com/tutorial/2017/02/18/how-to-create-user-sign-up-view.html
def register_user(request):
    """
    Allows a new user object to be created using a username and password entered
    into the registration form. This is then posted to the server to be added to
    the database of users.
    """
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('home:home')
    else:
        form = UserCreationForm()
    return render(request, 'authentication/registration.html', {'form': form})


def logout_view(request):
    """
    Logs a user out and returns them to the home page
    """
    logout(request)
    return redirect('home:home')

blog/templates/blog.html
{% extends "base.html" %}
{% block content %}
    {% for post in object_list %}
    <h5>{{ post.date|date:"Y-m-d" }}<a href="/blog/{{post.id}}">
        {{ post.title }}</a></h5>
    <hr/>
    {% endfor %}
{% endblock %}

blog/templates/comments.html
{% extends "post.html" %}
{% block content %}
<h3><a href="/blog/{{post.id}}">{{ post.title }}</a></h3>
<h6> on {{ post.date }}</h6>
<div class = "container">
  {{ post.body|safe|linebreaks}}
</div>
<h6 class="fw-light"> Posted by - {{ post.author }}</h6>
<span><a href="/blog">Return</a></span>
<br><br>
{% for comment in comments %}
  <div class="comments" style="padding: 10px;">
    <p class="font-weight-bold">
      {{ comment.name }}
      <span class=" text-muted font-weight-normal">
        {{ comment.created_on }}
      </span>
    </p>
    {{ comment.body | linebreaks }}
  </div>
{% endfor %}
{% endblock %}

blog/templates/post.html
{% extends "base.html" %}
{% block content %}
<h3><a href="/blog/{{blog_post.id}}">{{ post.title }}</a></h3>
<h6> on {{ post.date }}</h6>
<div class = "container">
  {{ post.body|safe|linebreaks}}
</div>
<h6 class="fw-light"> Posted by - {{ post.author }}</h6>
<span><a href="/blog">Return</a></span>
<br><br>
<!-- COMMENTS  -->
<h4>Leave your comment!</h4>
<div id="comments_section">

  {% if user.is_authenticated %}
  <form method="POST">
    {% csrf_token %}
    <div class="form-group">
      {{ comment_form }}
      <button class="btn btn-info" type="submit">Add comment</button>
    </div>
  </form>
  {% else %}
  <a class="btn btn-outline-info" href="{% url 'user_auth:login' %}?next={{request.path}}">
    Log in to add a comment!</a><br>
  {% endif %}

  {% if comments %}
  <strong class="text-secondary">{{ object.number_of_comments }} Comment{{ object.number_of_comments|pluralize }}</strong>
  <hr>
  <ul>
    {% for comment in comments %}
    <li>
     <div>
        <span>
          <strong class="text-info">{{ comment.author }} </strong>
          <small class="text-muted">{{ comment.date_posted }}</small>
        </span>
        <p>
          {{ comment.body|safe }}
        </p>
      </div>
    </li>
    {% endfor %}
  </ul>
  {% else %}
    <strong class="text-secondary">No comments yet...</strong>
  {% endif %}
</div>

{% endblock %}

home/templates/index.html
{% extends "base.html" %}
{% block content %}
<div>
    <h1> What is Pauper? </h1>
</div>
<div class="row">
    <div class="col-md"></div>
    <p>Pauper is just one of many of Magic the Gathering's different rulesets, known as a format.
        While it has a long history as a community-led format on Magic Online,
        it was only acknowledged by Wizards of the Coast for tabletop play in 2019.
    </p>
    <p>
        Despite that, it's become one of the most-loved formats in the game.
        Between the constant events for it on Magic Online and the introduction of the Pauper Format Panel in
        early 2022, Pauper looks like it's going to get bigger than ever.
    </p>
    <p>
        Pauper is a one-on-one, eternal, competitive format in the same vein as something like Legacy, Modern,
        or Vintage. Starting at 20 life each, two players draw seven cards from a deck at least 60 cards big and try to
        win through combat or combos. If you've played virtually any other Magic the Gathering format
        (bar a multiplayer format like Commander), you know the general flow of a Pauper game already.
    </p>
    <p>
        The big 'gimmick' of Pauper, though, is in which cards are legal in it. While it never rotates like Standard,
        meaning cards from right across the game's history can be used, only common-rarity cards are legal. Uncommon,
        rare, and mythic rare cards have no place in the Pauper format.
    </p>
    <p>
        For a card to be legal in Pauper, at least one of its printings has to have been at common rarity.
        As long as that is the case, every printing of the card is legal in Pauper. For instance,
        Brainstorm was 'upshifted' from common to rare in Strixhaven's Mystical Archive, but you can still play the
        Mystical Archive version in Pauper because of its earlier, common versions.
    </p>
    </div>
</div>
<hr>
<div class="row">
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Prince of Pauper</title>
  <!-- Bootstrap -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
</head>
<body class="bg-light">
<!-- Header -->
<div class="row p-3 mb-2 bg-secondary bg-gradient font-weight-bold text-light">
    <div class="col-md my-auto">
    <a href="{% url 'home:home' %}">
        <img class="img-fluid" src="{% static 'assets/popLogo.png' %}"  id="logo" alt="Logo">
    </a>
    </div>
    <!-- Site Navigation -->
    <div class="col-md align-self-center text-center">
        <a class="btn btn-outline-light " href="{% url 'home:home' %}">
            Home
        </a>
        <a class="btn btn-outline-light" href="{% url 'blog:blog' %}">
            Articles
        </a>
        <!-- Login and register buttons, displays username and logout button instead when someone is logged in -->
            {% if user.is_authenticated %}
                {{ request.user }}
                <a href="#" onClick="document.getElementById('logout-form').submit()">
                    <button type="button" class="btn btn-outline-light">Logout</button>
                </a>
                <form id="logout-form" method="POST" action="{% url 'user_auth:logout_user' %}">
                    {% csrf_token %}
                    <input type="hidden">
                </form>
            {% else %}
            <a class="btn btn-outline-light" href="{% url 'user_auth:register_user' %}">Register</a>
            <a class="btn btn-outline-light" href="{% url 'user_auth:login' %}">login</a>
            {% endif %}
        </div>
</div>

<!-- Content -->
<div class="container">
    <div class="row mt-5">
        <div class="col">
            {% block content %}
            {% endblock %}
        </div>
    </div>
</div>

</body>

user_auth/templates/authentication/login.html
{% extends 'base.html' %}

{% block content %}
<h1> Login as User </h1>
  <form action="{% url 'user_auth:authenticate_user' %}" method="post">
  {% csrf_token %}

  <label>Username</label>
  <input type="text" name="username" placeholder="User" required>
  <br/><br/>

  <label>Password</label>
  <input type="password" name="password" required>
  <br/><br/>

  <input class="btn btn-secondary" type="submit" value="Login" />
  <a class="btn btn-secondary" href="{% url 'user_auth:register_user' %}">
    Register
  </a>
</form>
{% endblock %}

user_auth/templates/authentication/registration.html
{% extends 'base.html' %}

{% block content %}
  <h2>Register</h2>
  <form method="post">
    {% csrf_token %}
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <button class="btn btn-secondary" type="submit">Register</button>
  </form>
{% endblock %}